### ISSUE TITLE
Problems in reproducing example

### ISSUE THREAD

**Issue by ghost** [patperu/effisr#1]
Hi,
I'm just trying the library, it works very well in getting data, but i have to test it deeply yet.

i was testing the main example, and i have some problems running geom_sf() in:

> ggplot() +
      geom_sf(aes(fill = area_ha)) +
      ggtitle("Fire") +
      theme(legend.position="bottom")

i get the error:

> Error in if (st_is_longlat(crs)) bb = trim_bb(bb, margin) : 
missing value whereTRUE/FALSE is request

I think is a ggplot develop version bug as you can see here: [https://github.com/tidyverse/ggplot2/issues/2060](https://github.com/tidyverse/ggplot2/issues/2060)

Edzer resolves the problem adding the attribute coord_sf()
So the plot should be:
`x %>%
      ggplot() +
      geom_sf(aes(fill = area_ha)) +
      ggtitle("Fire") +
      theme(legend.position="bottom")+
      coord_sf(crs = sf::st_crs(x))`

but i get the error

> Error in st_transform.sfc(layer_data$geometry, params$crs) : 
  sfc object should have crs set

I discover that the sfc didn't have crs set then i just add it:

> x <- tibble::as_tibble(res$docs) %>%
     sf::st_as_sf(coords = c("lon", "lat")) %>% 
     sf::st_set_crs( 4326)

I think (hope) 4326 is the correct crs but i don't find any metadata in the effis website.

Btw, when i try to run the ggplot i get the same error

> Error in st_transform.sfc(layer_data$geometry, params$crs) : 
  sfc object should have crs set

I attach my sessionInfo()

> R version 3.3.3 (2017-03-06)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 17.04

> locale:
 [1] LC_CTYPE=it_IT.UTF-8       LC_NUMERIC=C               LC_TIME=it_IT.UTF-8        LC_COLLATE=it_IT.UTF-8    
 [5] LC_MONETARY=it_IT.UTF-8    LC_MESSAGES=it_IT.UTF-8    LC_PAPER=it_IT.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=it_IT.UTF-8 LC_IDENTIFICATION=C       

> attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

> other attached packages:
[1] ggplot2_2.2.1.9000 scales_0.4.1.9002  effisr_0.1.0.9000  sf_0.5-2          

> loaded via a namespace (and not attached):
 [1] Rcpp_0.12.12     plyr_1.8.4       git2r_0.18.0     bindr_0.1        tools_3.3.3      digest_0.6.12   
 [7] jsonlite_1.5     evaluate_0.10.1  memoise_1.1.0    tibble_1.3.3     gtable_0.2.0     pkgconfig_2.0.1 
[13] rlang_0.1.1      DBI_0.7          mapproj_1.2-5    curl_2.7         yaml_2.1.14      bindrcpp_0.2    
[19] withr_1.0.2      httr_1.2.1       stringr_1.2.0    dplyr_0.7.1      knitr_1.16       maps_3.2.0      
[25] devtools_1.13.2  hms_0.3          rprojroot_1.2    grid_3.3.3       glue_1.1.1       R6_2.2.2        
[31] rmarkdown_1.6    readr_1.1.1      udunits2_0.13    magrittr_1.5     backports_1.1.0  htmltools_0.3.6 
[37] units_0.4-5      rsconnect_0.8    assertthat_0.2.0 colorspace_1.3-2 labeling_0.3     stringi_1.1.5   
[43] lazyeval_0.2.0   munsell_0.4.3

**Comment by patperu** [comment]
Hi Andrea,
thanks for using the "package" 😄 - it is definitely in alpha stage.... 
Can you please try the develpopment version of 'sf', it should be '0.5-3'. This is the version I'm using.

P.S. I edited your comment to point to the correct ggplot issue

``` r
devtools::session_info()
```

    ## Session info -------------------------------------------------------------

    ##  setting  value                                      
    ##  version  R version 3.4.1 Patched (2017-07-15 r72924)
    ##  system   x86_64, mingw32                            
    ##  ui       RTerm                                      
    ##  language (EN)                                       
    ##  collate  German_Germany.1252                        
    ##  tz       Europe/Berlin                              
    ##  date     2017-07-21

    ## Packages -----------------------------------------------------------------

    ##  package    * version    date       source                            
    ##  assertthat   0.2.0      2017-04-11 CRAN (R 3.4.1)                    
    ##  backports    1.1.0      2017-05-22 CRAN (R 3.4.0)                    
    ##  base       * 3.4.1      2017-07-19 local                             
    ##  bindr        0.1        2016-11-13 CRAN (R 3.4.1)                    
    ##  bindrcpp     0.2        2017-06-17 CRAN (R 3.4.1)                    
    ##  colorspace   1.3-2      2016-12-14 CRAN (R 3.4.1)                    
    ##  compiler     3.4.1      2017-07-19 local                             
    ##  curl         2.7        2017-06-26 CRAN (R 3.4.1)                    
    ##  datasets   * 3.4.1      2017-07-19 local                             
    ##  DBI          0.7        2017-06-18 CRAN (R 3.4.1)                    
    ##  devtools     1.13.2     2017-06-02 CRAN (R 3.4.1)                    
    ##  digest       0.6.12     2017-01-27 CRAN (R 3.4.1)                    
    ##  dplyr        0.7.1      2017-06-22 CRAN (R 3.4.1)                    
    ##  effisr     * 0.1.0.9000 2017-07-21 local                             
    ##  evaluate     0.10.1     2017-06-24 CRAN (R 3.4.1)                    
    ##  ggplot2    * 2.2.1.9000 2017-07-21 Github (tidyverse/ggplot2@331977e)
    ##  glue         1.1.1      2017-06-21 CRAN (R 3.4.1)                    
    ##  graphics   * 3.4.1      2017-07-19 local                             
    ##  grDevices  * 3.4.1      2017-07-19 local                             
    ##  grid         3.4.1      2017-07-19 local                             
    ##  gtable       0.2.0      2016-02-26 CRAN (R 3.4.1)                    
    ##  hms          0.3        2016-11-22 CRAN (R 3.4.1)                    
    ##  htmltools    0.3.6      2017-04-28 CRAN (R 3.4.1)                    
    ##  httr         1.2.1      2016-07-03 CRAN (R 3.4.1)                    
    ##  jsonlite     1.5        2017-06-01 CRAN (R 3.4.1)                    
    ##  knitr        1.16       2017-05-18 CRAN (R 3.4.1)                    
    ##  labeling     0.3        2014-08-23 CRAN (R 3.4.0)                    
    ##  lazyeval     0.2.0      2016-06-12 CRAN (R 3.4.1)                    
    ##  magrittr     1.5        2014-11-22 CRAN (R 3.4.1)                    
    ##  memoise      1.1.0      2017-04-21 CRAN (R 3.4.1)                    
    ##  methods    * 3.4.1      2017-07-19 local                             
    ##  munsell      0.4.3      2016-02-13 CRAN (R 3.4.1)                    
    ##  pkgconfig    2.0.1      2017-03-21 CRAN (R 3.4.1)                    
    ##  plyr         1.8.4      2016-06-08 CRAN (R 3.4.1)                    
    ##  R6           2.2.2      2017-06-17 CRAN (R 3.4.1)                    
    ##  Rcpp         0.12.12    2017-07-15 CRAN (R 3.4.1)                    
    ##  readr        1.1.1.9000 2017-07-19 Github (hadley/readr@3ea8199)     
    ##  rlang        0.1.1      2017-05-18 CRAN (R 3.4.1)                    
    ##  rmarkdown    1.6.0.9001 2017-07-19 Github (rstudio/rmarkdown@8cfe0cb)
    ##  rprojroot    1.2        2017-01-16 CRAN (R 3.4.1)                    
    ##  scales       0.4.1.9002 2017-07-19 Github (hadley/scales@6db7b6f)    
    ##  sf         * 0.5-3      2017-07-21 Github (edzer/sfr@798068d)        
    ##  stats      * 3.4.1      2017-07-19 local                             
    ##  stringi      1.1.5      2017-04-07 CRAN (R 3.4.0)                    
    ##  stringr      1.2.0      2017-02-18 CRAN (R 3.4.1)                    
    ##  tibble       1.3.3      2017-05-28 CRAN (R 3.4.1)                    
    ##  tools        3.4.1      2017-07-19 local                             
    ##  udunits2     0.13       2016-11-17 CRAN (R 3.4.0)                    
    ##  units        0.4-5      2017-06-15 CRAN (R 3.4.1)                    
    ##  utils      * 3.4.1      2017-07-19 local                             
    ##  withr        1.0.2      2016-06-20 CRAN (R 3.4.1)                    
    ##  yaml         2.1.14     2016-11-12 CRAN (R 3.4.1)

**Comment by ghost** [comment]
ok, now it's working!

**Comment by patperu** [comment]
Great!
